# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ImageTransmission.image_transmit_pb2 as image__transmit__pb2


class TransmitImageAndDataStub(object):
    """Image Transmission RPC.

    Sends a payload containing the image and metadata
    including timestamp and GPS coordinates.
    Future implementations might use 'streams' to
    better handle chunking or customize chunk sizes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendData = channel.unary_unary(
                '/ImageTransmission.TransmitImageAndData/SendData',
                request_serializer=image__transmit__pb2.ImageDataRequest.SerializeToString,
                response_deserializer=image__transmit__pb2.ImageDataResponse.FromString,
                )


class TransmitImageAndDataServicer(object):
    """Image Transmission RPC.

    Sends a payload containing the image and metadata
    including timestamp and GPS coordinates.
    Future implementations might use 'streams' to
    better handle chunking or customize chunk sizes.
    """

    def SendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransmitImageAndDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=image__transmit__pb2.ImageDataRequest.FromString,
                    response_serializer=image__transmit__pb2.ImageDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageTransmission.TransmitImageAndData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransmitImageAndData(object):
    """Image Transmission RPC.

    Sends a payload containing the image and metadata
    including timestamp and GPS coordinates.
    Future implementations might use 'streams' to
    better handle chunking or customize chunk sizes.
    """

    @staticmethod
    def SendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageTransmission.TransmitImageAndData/SendData',
            image__transmit__pb2.ImageDataRequest.SerializeToString,
            image__transmit__pb2.ImageDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
