# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_transmit_pb2 as image__transmit__pb2


class TransmitTimeAndGPSStub(object):
    """Simple RPC.

    Sends the timestamp and GPS coordinates of an image
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendData = channel.unary_unary(
                '/TransmitTimeAndGPS/SendData',
                request_serializer=image__transmit__pb2.TimeGPSRequest.SerializeToString,
                response_deserializer=image__transmit__pb2.TimeGPSResponse.FromString,
                )


class TransmitTimeAndGPSServicer(object):
    """Simple RPC.

    Sends the timestamp and GPS coordinates of an image
    """

    def SendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransmitTimeAndGPSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=image__transmit__pb2.TimeGPSRequest.FromString,
                    response_serializer=image__transmit__pb2.TimeGPSResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TransmitTimeAndGPS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransmitTimeAndGPS(object):
    """Simple RPC.

    Sends the timestamp and GPS coordinates of an image
    """

    @staticmethod
    def SendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TransmitTimeAndGPS/SendData',
            image__transmit__pb2.TimeGPSRequest.SerializeToString,
            image__transmit__pb2.TimeGPSResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
