# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image-transmit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image-transmit.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14image-transmit.proto\"$\n\x0eTimeGPSRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"K\n\x0fTimeGPSResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x11\n\tgpscoords\x18\x03 \x01(\t2E\n\x12TransmitTimeAndGPS\x12/\n\x08SendData\x12\x0f.TimeGPSRequest\x1a\x10.TimeGPSResponse\"\x00\x62\x06proto3'
)




_TIMEGPSREQUEST = _descriptor.Descriptor(
  name='TimeGPSRequest',
  full_name='TimeGPSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='TimeGPSRequest.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=60,
)


_TIMEGPSRESPONSE = _descriptor.Descriptor(
  name='TimeGPSResponse',
  full_name='TimeGPSResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='TimeGPSResponse.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TimeGPSResponse.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpscoords', full_name='TimeGPSResponse.gpscoords', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['TimeGPSRequest'] = _TIMEGPSREQUEST
DESCRIPTOR.message_types_by_name['TimeGPSResponse'] = _TIMEGPSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeGPSRequest = _reflection.GeneratedProtocolMessageType('TimeGPSRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIMEGPSREQUEST,
  '__module__' : 'image_transmit_pb2'
  # @@protoc_insertion_point(class_scope:TimeGPSRequest)
  })
_sym_db.RegisterMessage(TimeGPSRequest)

TimeGPSResponse = _reflection.GeneratedProtocolMessageType('TimeGPSResponse', (_message.Message,), {
  'DESCRIPTOR' : _TIMEGPSRESPONSE,
  '__module__' : 'image_transmit_pb2'
  # @@protoc_insertion_point(class_scope:TimeGPSResponse)
  })
_sym_db.RegisterMessage(TimeGPSResponse)



_TRANSMITTIMEANDGPS = _descriptor.ServiceDescriptor(
  name='TransmitTimeAndGPS',
  full_name='TransmitTimeAndGPS',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=139,
  serialized_end=208,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendData',
    full_name='TransmitTimeAndGPS.SendData',
    index=0,
    containing_service=None,
    input_type=_TIMEGPSREQUEST,
    output_type=_TIMEGPSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSMITTIMEANDGPS)

DESCRIPTOR.services_by_name['TransmitTimeAndGPS'] = _TRANSMITTIMEANDGPS

# @@protoc_insertion_point(module_scope)
